### ISSUE TITLE
`cleanup` function in the core code

### ISSUE THREAD

**Issue by curio-sitas** [petvana/AutoSysimages.jl#21]
There is a **clean.sh** file in the repo. As the package creates many files in projects folder and julia bin directory, it would be nice to have a `cleanup` routine in the code as a **functionality** of the package.

Example : 
```
julia> using AutoSysimages
julia> AutoSysimages.cleanup()
```
Should remove all the files and directory created by the package, including the asysimg script

**Comment by petvana** [comment]
My proposal:

- `uninstall()`
  - Remove what `install()` created
- `cleanup()`
  - Remove directory `joinpath(DEPOT_PATH[1], "asysimg")`
  - ~~Remove all `SysimagePreferences.toml` files~~ **Edit** Preference files are not removed in the PR

However, removing all `SysimagePreferences.toml` files in your computer is slightly more complicated, but there is already path to the project.

**Comment by ufechner7** [comment]
This is really important. After upgrading this package I am not able to make it work again, probably because of some old files lying around somewhere...
