### ISSUE TITLE
Scripts missing?

### ISSUE THREAD

**Issue by Schinkikami** [petvana/AutoSysimages.jl#31]
Hey @petvana, 

I love your project, directly tested it somtime last month, when I saw your package annoucement. However, when I now install the package 
 `] add AutoSysimages ` or directly the github repository
and I use
`Autosysimages.start()` followed by some commands and then `Autosysimages.build_sysimages()` it throws the following error.

    ERROR: IOError: could not spawn `asysimg -J /opt/julia-1.8.2/lib/julia/sys.so -e '' --trace-compile /tmp/jl_RGLarUfsnM`: no such file or directory (ENOENT)
    Stacktrace:
      [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Union{RawFD, IO}})
        @ Base ./process.jl:128
      [2] #725
        @ ./process.jl:139 [inlined]
      [3] setup_stdios(f::Base.var"#725#726"{Cmd}, stdios::Vector{Union{RawFD, IO}})
        @ Base ./process.jl:223
      [4] _spawn
        @ ./process.jl:138 [inlined]
      [5] run(::Cmd; wait::Bool)
        @ Base ./process.jl:479
      [6] run
        @ ./process.jl:477 [inlined]
      [7] _build_system_image()
        @ AutoSysimages ~/.julia/packages/AutoSysimages/CtLWM/src/AutoSysimages.jl:573
      [8] build_sysimage(background::Bool)
        @ AutoSysimages ~/.julia/packages/AutoSysimages/CtLWM/src/AutoSysimages.jl:196
      [9] build_sysimage()
        @ AutoSysimages ~/.julia/packages/AutoSysimages/CtLWM/src/AutoSysimages.jl:166
     [10] top-level scope
        @ REPL[4]:1

The same happens when I exit the REPL (`^D`) and the interactive promt appears.
It seems the asysimg script is just missing? I could also not see it in the repository, on older commits it is still there. 
Am I missing something?

**Comment by petvana** [comment]
Thank you for your interest. I've changed (simplify) the installation process. Please try to run in normal Julia the following
``` julia
using AutoSysimages
install()
```
