### ISSUE TITLE
Add function install()

### ISSUE THREAD

**Issue by ufechner7** [petvana/AutoSysimages.jl#4]
Add a function that copies the required script at the suggested location.

Should be trivial for Linux.

**Comment by ufechner7** [comment]
You can find an example here: https://github.com/ufechner7/Plotting/blob/main/bin/install

**Comment by petvana** [comment]
Here, I'd prefer Julia function, i.e., `AutoSysimages.install()`.

**Comment by ufechner7** [comment]
Yes, Julia is cross platform, thats better...

Some example code from another project of me:
```julia
function cp_examples()
    PATH = "examples"
    src_path = joinpath(dirname(pathof(@__MODULE__)), "..", PATH)
    copy_files("examples", readdir(src_path))
end

function copy_files(relpath, files)
    if ! isdir(relpath) 
        mkdir(relpath)
    end
    src_path = joinpath(dirname(pathof(@__MODULE__)), "..", relpath)
    for file in files
        cp(joinpath(src_path, file), joinpath(relpath, file), force=true)
        chmod(joinpath(relpath, file), 0o774)
    end
    files
end
```

**Comment by petvana** [comment]
I've drafted a PR. Btw, the `chmod` seems not necessary.

**Comment by ufechner7** [comment]
I also drafted a PR, but you were faster and a bit better...
Small remark: There is a typo in the title of your PR, it should be install() and not instal().
