### ISSUE TITLE
Unable to save/load sysimage

### ISSUE THREAD

**Issue by petvana** [petvana/AutoSysimages.jl#5]
@ufechner7 reported this issue at [forum](https://discourse.julialang.org/t/autosysimages-jl-automate-user-specific-system-images/87359/17):

To be honest, I do not see ANY effect from using AutoSysimages.

What I did (on Ubuntu):

    install AutoSysimages
    change folder of my work project
    run asysimg --project
    run include(“src/plot.jl”) from the asysimage prompt
    close the plot window
    press <ctrl>+<d>
    I get the message:

asysimg> 
[ Info: AutoSysimages: Copy snooped statements to: /home/ufechner/.julia/asysimg/1.8.1/23RTv7/snoop-file.jl
[ Info: There is no sysimage for this project. Do you want to build one?
 > Yes
   No

I press enter and select No for the next question (do you want to select packages).

Now it builds a system image.

[ Info: AutoSysimages: Copy snooped statements to: /home/ufechner/.julia/asysimg/1.8.1/23ZRuw/snoop-file.jl
[ Info: There is no sysimage for this project. Do you want to build one?
 > Yes
   No
[ Info: AutoSysimages: Collecting precompile statements for empty run (-e "")
[ Info: AutoSysimages: Building system image by PackageCompiler.
⠇ [00m:10s] PackageCompiler: compiling incremental system image┌ Warning: There is no statement file
└ @ Main.anonymous /home/ufechner/.julia/packages/AutoSysimages/LTaGS/src/precompile-PackageCompiler.jl:44

✔ [02m:25s] PackageCompiler: compiling incremental system image
[ Info: AutoSysimages: Builded in 147.87036108970642 s

If I now launch julia again and run the same include statement the time to first plot is 17s as before:

ufechner@TUD277255:~/repos/Plotting$ asysimg --project
┌ Info: The package AutoSysimages.jl started!
│  Loaded sysimage:    Default (You may run AutoSysimages.build_sysimage())
│  Active directory:   /home/ufechner/.julia/asysimg/1.8.1/23ZRuw
│  Global snoop file:  /home/ufechner/.julia/asysimg/1.8.1/23ZRuw/snoop-file.jl
└  Tmp. snoop file:    /tmp/jl_gJmh8ds5yB-snoop.jl
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.1 (2022-09-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

asysimg> @time include("src/plot.jl")
To zoom, draw a rectangle while keeping the right mouse key pressed!
To go back to see the full graph, press <CRTRL><f>
 17.618484 seconds (43.41 M allocations: 2.397 GiB, 4.78% gc time, 71.93% compilation time: 12% of which was recompilation)

You can find and clone the example project I used here: [GitHub - ufechner7/Plotting](https://github.com/ufechner7/Plotting)

My impression is that it creates a sysimage, but it does not use it later.

Any idea?

**Comment by ufechner7** [comment]
This issue disappeared, I assume because I added the package Plots to my project file, see latest version of https://github.com/ufechner7/Plotting.

But the speed gain is still not as high as expected:
```
asysimg> @time include("src/plot.jl")
To zoom, draw a rectangle while keeping the right mouse key pressed!
To go back to see the full graph, press <CRTRL><f>
 11.709348 seconds (28.54 M allocations: 1.523 GiB, 4.72% gc time, 78.63% compilation time: 3% of which was recompilation)
```
compared to
```
julia> @time include("src/plot.jl")
To zoom, draw a rectangle while keeping the right mouse key pressed!
To go back to see the full graph, press <CRTRL><f>
 15.501547 seconds (38.28 M allocations: 2.051 GiB, 4.30% gc time, 78.86% compilation time: 12% of which was recompilation)
```

**Comment by ufechner7** [comment]
The issue re-appeared when trying the same on a different computer...
```
ufechner@tuxedi:~/repos/Plotting$ asysimg --project
┌ Info: The package AutoSysimages.jl started!
│  Loaded sysimage:    Default (You may run AutoSysimages.build_sysimage())
│  Active directory:   /home/ufechner/.julia/asysimg/1.8.1/23ZRuw
│  Global snoop file:  /home/ufechner/.julia/asysimg/1.8.1/23ZRuw/snoop-file.jl
└  Tmp. snoop file:    /tmp/jl_dIbgFQJiJo-snoop.jl
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.1 (2022-09-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

asysimg> 

asysimg> using AutoSysimages
asysimg> latest_sysimage()
"/home/ufechner/.julia/asysimg/1.8.1/23ZRuw/asysimg-2022-09-18T00-41-33.838.so"

asysimg> julia_args()
" -J /home/ufechner/.julia/asysimg/1.8.1/23ZRuw/asysimg-2022-09-18T00-41-33.838.so -L /home/ufechner/.julia/packages/AutoSysimages/LTaGS/src/start.jl"
asysimg> 
```

**Comment by petvana** [comment]
I'm sorry. This is kind of embarrassing bug. The initialize script should contain `"$@"` at the and to propagate the `--project` argument. I've removed it during testing and didn't put it back before the release.
```
asysimg_args=`$JULIA_EXE -e "using AutoSysimages; print(julia_args()); exit();" "$@"`
```

**Comment by ufechner7** [comment]
Great that you found the reason! :)

**Comment by ufechner7** [comment]
Are you sure this fix is correct:
```bash
asysimg_args=`$JULIA_EXE -e "using AutoSysimages; print(julia_args()); exit();" "$@"`
```
I get the message:
```
ufechner@TUD277255:~/repos/Plotting$ asysimg --project
/home/ufechner/.local/bin/asysimg: line 3: unexpected EOF while looking for matching ``'
/home/ufechner/.local/bin/asysimg: line 5: syntax error: unexpected end of file
```
